#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     elevator,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     right,         tmotorTetrix, openLoop)
#pragma config(Sensor, S2,     Gyro,           sensorI2CHiTechnicGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "config.c"
#include "drivetrain.c"
#include "gyro.c"

void initializeRobot()
{
	resetEncoders();

  return;
}

void driveDistance(int setpoint) {
	int wheelDiameter = 3;

//	setpoint /= PI*(float)wheelDiameter;
	//setpoint *=
	//setpoint = (int) setpoint;

	int maxSpeed = 100;

	int distanceL = setpoint - leftEnc;
	int distanceR = setpoint - leftEnc;

	float distAttenuation = 0.01;
	//Max Speed:		AttenuationValue:
	//50						.01
	//75						.01
	//100
	int outputL = (int)((float)maxSpeed * (1 - pow(2.718, -distAttenuation*(float)abs(distanceL))))*sgn(distanceL);
	int outputR = (int)((float)maxSpeed * (1 - pow(2.718, -distAttenuation*(float)abs(distanceR))))*sgn(distanceR);
  tankDrive(outputL, outputR);
}

task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

  while (true)
  {
  	driveDistance(360);
  	wait1Msec(5);
  }
}
