#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C2_1,     elevator,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     right,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    rampLatch,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    platLatch,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
#include "config.c"
#include "drivetrain.c"



task main()
{
	servo[rampLatch] = 20;

			servo[platLatch] = 255;
  waitForStart(); // Wait for the beginning of autonomous phase.
	initDrivetrain();
	wait1Msec(100);
	ClearTimer(T1);
	while(time1[T1] < 2000) {
		driveDistance(54, 100);
	}

	ClearTimer(T1);
	while(time1[T1] < 1200) {
		driveAngle(120.0, 80, getAngle());
	}

	ClearTimer(T1);
	resetEncoders();
	while(time1[T1] < 3000) {
		driveDistance(48, 100);
	}

	while(true){}

}
