#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     elevator,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     right,         tmotorTetrix, openLoop)
#pragma config(Sensor, S2,     Gyro,           sensorI2CHiTechnicGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
#include "config.c"
#include "drivetrain.c"



task main()
{
  waitForStart(); // Wait for the beginning of autonomous phase.
	initDrivetrain();
	wait1Msec(100);
	ClearTimer(T1);
	while(time1[T1] < 2000) {
		driveDistance(54, 100);
	}

	ClearTimer(T1);
	while(time1[T1] < 1200) {
		driveAngle(120.0, 80, getAngle());
	}

	ClearTimer(T1);
	resetEncoders();
	while(time1[T1] < 3000) {
		driveDistance(48, 100);
	}


}
