#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     elevator,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     right,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
#include "config.c"
#include "drivetrain.c"



task main()
{
  waitForStart(); // Wait for the beginning of autonomous phase.

	ClearTimer(T1);
	tankDrive(100, 85);
	wait1Msec(1800);
	tankDrive(100, -70);
	wait1Msec(500);
	tankDrive(100, 85);
	wait1Msec(1200);
	tankDrive(-100, -85);
	wait1Msec(1200);
	tankDrive(100, 85);
	wait1Msec(600);
	tankDrive(-100, 100);
	wait1Msec(5000);

	tankDrive(0, 0);
}
