#pragma config(Sensor, S1,     Gyro,           sensorI2CHiTechnicGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "gyro.c"

task main()
{
	StartTask(GyroTask);
	while(true) {
		writeDebugStreamLine("Angle is : %f", getAngle());
		wait1Msec(1000);
	}

}
