#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     HTPB,                sensorI2CCustom9V)
#pragma config(Motor,  mtr_S1_C2_1,     elevator,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     right,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    rampLatch,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    platLatch,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
#include "config.c"
#include "drivetrain.c"
#include "elevator.c"
#include "SignalLightStrip.c"


task main()
{
	StartTask(SignalLight);
	setMode(IDLE);
	servo[rampLatch] = 20;


	servo[platLatch] = 255;
	waitForStart(); // Wait for the beginning of autonomous phase.
	initDrivetrain();

	initElevator();
	StartTask(ElevatorControlTask);	//begin elevator control task

	isOpenLoop = false;
	closedLoopInput(MID, true);

	wait1Msec(100);
	ClearTimer(T1);
	while(time1[T1] < 2500) {
		driveDistance(72, 100);	//Initial drive forward to rack
		setMode(ACTIVE);
	}

setMode(CRITICAL);

	closedLoopInput(MID - 50, true);

	wait1Msec(250);

	ClearTimer(T1);
	while(time1[T1] < 3000) {
		setMode(SUPER_CRITICAL);
		driveDistance(54, 75);
	}
closedLoopInput(STOW, true);
	while(true){}

}
