#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     elevator,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     right,         tmotorTetrix, openLoop)
#pragma config(Sensor, S2,     Gyro,           sensorI2CHiTechnicGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "config.c"
#ifdef configured
#include "Drivetrain.c"
#include "elevator.c"

#define STOW_BTN 1
#define GRAB_BTN 2
#define MID_BTN 3
#define TOP_BTN 4

/* Title: operator
 * Parameters: none
 * Returns: none
 * Description: encloses operator commands in one function for easy tweaking
 */
void operator() {
	int rawJoystick = 0;														//Open Loop Joystick input
	rawJoystick += (joystick.joy2_y2*100)/128;
	rawJoystick -= ((joystick.joy2_y1*100)/128)/3;

	if(joy2Btn(STOW_BTN)) {				//Logic for choosing setpoints or open loop control
		closedLoopInput(STOW, true);
	} else if(GRAB_BTN) {
		closedLoopInput(GRAB, true);
	} else if(MID_BTN) {
		closedLoopInput(MID, true);
	} else if(TOP_BTN) {
		closedLoopInput(TOP, true);
	} else {
		openLoopInput(rawJoystick);
	}
}

/* Title: main
 * Parameters: none
 * Returns: none
 * Description: main task. initiates auxillary tasks and contains driver inputs
 */
task main() {
	ClearTimer(T1);	 //Clear timer 1 for checking to see how long the robot waits before starting
	initDrivetrain();//Initialize systems
	initElevator();
	StartTask(ElevatorControlTask);	//begin elevator control task

	waitForStart(); //Wait for FCS start

	if(time1[T1] >= 60000)  {	//if robot has been sitting for a while before startin, call init again to zero and reset gyro and encoders
		initDrivetrain();
		initElevator();
	}

	ClearTimer(T1);	//Clear Timer 1 for robot functions before operation starts
	while(true) {
		getJoystickSettings(joystick);	//Get FCS controller data
		operator();	//Run operator commands

		int left = (joystick.joy1_y1*100)/128;		//Driver inputs, scaled to the motor controller input range of +- 100
		int right = (joystick.joy1_y2*100)/128;

		tankDrive(left, right);

		writeDebugStream("Enabled for %f", (float)time1[T1]/1000.0);	//Enabled timer
		writeDebugStreamLine(" seconds");
	}
}
#endif
